"""``bsl init``: scaffold a starter rules.yaml and optional project config.

The starter is intentionally realistic — two checkout rules with
when/then clauses, entities, and affected services — so the first
``bsl validate`` passes and shows off the schema.
"""

from __future__ import annotations

from pathlib import Path

STARTER_RULES_YAML = '''\
# Starter business rules generated by bsl init.
name: starter-rules
version: "1.0.0"
description: Starter rule set — edit me.

rules:
  - id: checkout.min-order
    version: 1
    statement: Orders must be at least $10 before tax to checkout.
    when:
      - field: cart.subtotal
        op: lt
        value: 10
    then:
      - field: cart.checkout_allowed
        op: is_false
    entities:
      - cart
      - order
    affected_services:
      - checkout-api
      - storefront-web

  - id: checkout.free-shipping
    version: 1
    statement: Orders over $50 ship free.
    when:
      - field: cart.subtotal
        op: ge
        value: 50
    then:
      - field: cart.shipping_price
        op: eq
        value: 0
    entities:
      - cart
      - shipping
    affected_services:
      - checkout-api
      - shipping-service
'''

STARTER_CONFIG_YAML = '''\
# Project defaults for bsl. Edit to match your team.
default_services:
  - checkout-api
  - storefront-web
output_path: reports
'''

RULES_FILENAME = "rules.yaml"
CONFIG_FILENAME = ".bsl.yaml"


def write_starter(
    directory: str | Path,
    *,
    rules_name: str = RULES_FILENAME,
    config_name: str | None = CONFIG_FILENAME,
    force: bool = False,
) -> list[Path]:
    """Write starter files into ``directory``. Returns the paths written.

    Raises :class:`FileExistsError` if a target already exists and
    ``force`` is false.
    """
    base = Path(directory)
    base.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    rules_path = base / rules_name
    if rules_path.exists() and not force:
        raise FileExistsError(f"{rules_path} already exists (use --force to overwrite)")
    rules_path.write_text(STARTER_RULES_YAML, encoding="utf-8")
    written.append(rules_path)

    if config_name is not None:
        config_path = base / config_name
        if config_path.exists() and not force:
            raise FileExistsError(
                f"{config_path} already exists (use --force to overwrite)"
            )
        config_path.write_text(STARTER_CONFIG_YAML, encoding="utf-8")
        written.append(config_path)

    return written


__all__ = [
    "STARTER_RULES_YAML",
    "STARTER_CONFIG_YAML",
    "RULES_FILENAME",
    "CONFIG_FILENAME",
    "write_starter",
]
